CREATE USER myuser WITH PASSWORD '123';
CREATE DATABASE wallet_db OWNER myuser;

\c wallet_db;

CREATE SCHEMA wallet_chema AUTHORIZATION myuser;

GRANT USAGE ON SCHEMA wallet_chema TO myuser;
GRANT CREATE ON SCHEMA wallet_chema TO myuser;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA wallet_chema TO myuser;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA wallet_chema TO myuser;

ALTER DEFAULT PRIVILEGES IN SCHEMA wallet_chema GRANT ALL ON TABLES TO myuser;
ALTER DEFAULT PRIVILEGES IN SCHEMA wallet_chema GRANT ALL ON SEQUENCES TO myuser;

GRANT ALL PRIVILEGES ON DATABASE wallet_db TO myuser;